/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria uma conta e retorna tokens */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica e retorna tokens */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotaciona o par de tokens */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoga o refresh token informado */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna o usuário autenticado */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza o perfil do usuário */
        patch: operations["UsersController_updateProfile"];
        trace?: never;
    };
    "/api/v1/users/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna as settings do usuário */
        get: operations["UsersController_getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza (merge) as settings do usuário */
        patch: operations["UsersController_updateSettings"];
        trace?: never;
    };
    "/api/v1/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista a watchlist (paginada, filtro por mediaType) */
        get: operations["FavoritesController_list"];
        put?: never;
        /** Adiciona à watchlist (idempotente: 200 se já existir) */
        post: operations["FavoritesController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/{tmdbId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove da watchlist (idempotente) */
        delete: operations["FavoritesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os salvos (paginada, filtro por mediaType) */
        get: operations["SavedController_list"];
        put?: never;
        /** Salva um item (idempotente: 200 se já existir) */
        post: operations["SavedController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved/{tmdbId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove um salvo (idempotente) */
        delete: operations["SavedController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/continue-watching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista o rail Continue Watching (updatedAt desc) */
        get: operations["ContinueWatchingController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/continue-watching/{tmdbId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cria ou atualiza o progresso (upsert) */
        put: operations["ContinueWatchingController_upsert"];
        post?: never;
        /** Remove do Continue Watching (idempotente) */
        delete: operations["ContinueWatchingController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness check */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example Ada Lovelace */
            fullName: string;
            /** @example ada@mail.com */
            email: string;
            /** @example senhaForte123 */
            password: string;
        };
        UserEntity: {
            /** @example clx1abc000001 */
            id: string;
            /** @example ada@mail.com */
            email: string;
            /** @example Ada Lovelace */
            fullName: string;
            /** @example null */
            avatarUrl: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-01-15T10:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-15T10:00:00.000Z
             */
            updatedAt: string;
        };
        AuthResponseDto: {
            user: components["schemas"]["UserEntity"];
            /** @example eyJhbGciOiJIUzI1NiIs... */
            accessToken: string;
            /** @example eyJhbGciOiJIUzI1NiIs... */
            refreshToken: string;
        };
        LoginDto: {
            /** @example ada@mail.com */
            email: string;
            /** @example senhaForte123 */
            password: string;
        };
        RefreshTokenDto: {
            /** @example eyJhbGciOiJIUzI1NiIs... */
            refreshToken: string;
        };
        TokenPairDto: {
            /** @example eyJhbGciOiJIUzI1NiIs... */
            accessToken: string;
            /** @example eyJhbGciOiJIUzI1NiIs... */
            refreshToken: string;
        };
        UpdateUserDto: {
            /** @example Ada Byron */
            fullName?: string;
            /** @example https://cdn.app/avatar.png */
            avatarUrl?: string | null;
        };
        UserSettingsEntity: {
            /**
             * @example system
             * @enum {string}
             */
            theme: "system" | "light" | "dark";
            /** @example pt-BR */
            language: string;
            /** @example true */
            autoplayTrailers: boolean;
            /** @example false */
            adultContent: boolean;
        };
        UpdateSettingsDto: {
            /**
             * @example dark
             * @enum {string}
             */
            theme?: "system" | "light" | "dark";
            /** @example en-US */
            language?: string;
            /** @example false */
            autoplayTrailers?: boolean;
            /** @example true */
            adultContent?: boolean;
        };
        FavoriteEntity: {
            /** @example clf1abc000001 */
            id: string;
            /** @example 693134 */
            tmdbId: number;
            /**
             * @example movie
             * @enum {string}
             */
            mediaType: "movie" | "tv";
            /** @example Dune: Part Two */
            title: string;
            /** @example /poster.jpg */
            posterPath: Record<string, never> | null;
            /** @example /backdrop.jpg */
            backdropPath: Record<string, never> | null;
            /** @example 2024 */
            releaseYear: Record<string, never> | null;
            /** @example 8.4 */
            voteAverage: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-01-15T10:00:00.000Z
             */
            addedAt: string;
        };
        MediaSnapshotDto: {
            /** @example 693134 */
            tmdbId: number;
            /**
             * @example movie
             * @enum {string}
             */
            mediaType: "movie" | "tv";
            /** @example Dune: Part Two */
            title: string;
            /** @example /poster.jpg */
            posterPath?: Record<string, never> | null;
            /** @example /backdrop.jpg */
            backdropPath?: Record<string, never> | null;
            /** @example 2024 */
            releaseYear?: Record<string, never> | null;
            /** @example 8.4 */
            voteAverage?: Record<string, never> | null;
        };
        SavedEntity: {
            /** @example cls1abc000001 */
            id: string;
            /** @example 693134 */
            tmdbId: number;
            /**
             * @example movie
             * @enum {string}
             */
            mediaType: "movie" | "tv";
            /** @example Dune: Part Two */
            title: string;
            /** @example /poster.jpg */
            posterPath: Record<string, never> | null;
            /** @example /backdrop.jpg */
            backdropPath: Record<string, never> | null;
            /** @example 2024 */
            releaseYear: Record<string, never> | null;
            /** @example 8.4 */
            voteAverage: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-01-15T10:00:00.000Z
             */
            savedAt: string;
        };
        ContinueWatchingEntity: {
            /** @example clc1abc000001 */
            id: string;
            /** @example 12345 */
            tmdbId: number;
            /**
             * @example tv
             * @enum {string}
             */
            mediaType: "movie" | "tv";
            /** @example Shōgun */
            title: string;
            /** @example /poster.jpg */
            posterPath: Record<string, never> | null;
            /** @example 0.62 */
            progress: number;
            /** @example 42 */
            runtimeLeft: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-01-15T10:00:00.000Z
             */
            updatedAt: string;
        };
        UpsertContinueWatchingDto: {
            /**
             * @example tv
             * @enum {string}
             */
            mediaType: "movie" | "tv";
            /** @example Shōgun */
            title: string;
            /** @example /poster.jpg */
            posterPath?: Record<string, never> | null;
            /** @example 0.62 */
            progress: number;
            /** @example 42 */
            runtimeLeft?: Record<string, never> | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    UsersController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    UsersController_getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsEntity"];
                };
            };
        };
    };
    UsersController_updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsEntity"];
                };
            };
        };
    };
    FavoritesController_list: {
        parameters: {
            query?: {
                page?: number;
                /** @description Itens por página. Acima de 50 é capado em 50. */
                limit?: number;
                mediaType?: "movie" | "tv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteEntity"][];
                };
            };
        };
    };
    FavoritesController_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaSnapshotDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteEntity"];
                };
            };
        };
    };
    FavoritesController_remove: {
        parameters: {
            query?: {
                mediaType?: "movie" | "tv";
            };
            header?: never;
            path: {
                tmdbId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SavedController_list: {
        parameters: {
            query?: {
                page?: number;
                /** @description Itens por página. Acima de 50 é capado em 50. */
                limit?: number;
                mediaType?: "movie" | "tv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedEntity"][];
                };
            };
        };
    };
    SavedController_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaSnapshotDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedEntity"];
                };
            };
        };
    };
    SavedController_remove: {
        parameters: {
            query?: {
                mediaType?: "movie" | "tv";
            };
            header?: never;
            path: {
                tmdbId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContinueWatchingController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContinueWatchingEntity"][];
                };
            };
        };
    };
    ContinueWatchingController_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tmdbId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertContinueWatchingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContinueWatchingEntity"];
                };
            };
        };
    };
    ContinueWatchingController_remove: {
        parameters: {
            query?: {
                mediaType?: "movie" | "tv";
            };
            header?: never;
            path: {
                tmdbId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
